=== nbeeee/xutils/xutils/src/main/java/zcu/xutil/cfg/xutils-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT beans (array|bean|alias|import)+>
<!ELEMENT import (#PCDATA)>
<!ATTLIST import key CDATA #IMPLIED>
<!ELEMENT bean (arg*,(set|call)*,out?,aop?)>
<!ATTLIST bean id CDATA #IMPLIED>
<!ATTLIST bean class CDATA #IMPLIED>
<!ATTLIST bean cache (true|false) "true">
<!ATTLIST bean eager (true|false) "false">
<!ATTLIST bean method CDATA #IMPLIED>
<!ATTLIST bean destroy CDATA #IMPLIED>
<!ELEMENT array (arg*)>
<!ATTLIST array id CDATA #IMPLIED>
<!ATTLIST array cache (true|false) "false">
<!ATTLIST array class CDATA #REQUIRED>
<!ELEMENT alias (aop?)>
<!ATTLIST alias id CDATA #REQUIRED>
<!ATTLIST alias ref CDATA #REQUIRED>
<!ELEMENT set (#PCDATA|bean|array)*>
<!ATTLIST set property CDATA #REQUIRED>
<!ATTLIST set class CDATA #IMPLIED>
<!ATTLIST set ref CDATA #IMPLIED>
<!ELEMENT call (arg*)>
<!ATTLIST call method CDATA #REQUIRED>
<!ELEMENT out (arg*)>
<!ATTLIST out class CDATA #IMPLIED>
<!ATTLIST out method CDATA #REQUIRED>
<!ELEMENT aop (#PCDATA)>
<!ATTLIST aop class CDATA #IMPLIED>
<!ELEMENT arg (#PCDATA|bean|array)*>
<!ATTLIST arg class CDATA #IMPLIED>
<!ATTLIST arg ref CDATA #IMPLIED>

=== nbeeee/xutils/xutils/src/test/java/test.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE beans PUBLIC "-//XUTILS//DTD CONFIG//EN" "xutils-config.dtd">
<beans>
	<import key="mystore">MYSTORE java.lang.String</import>
	<import key="map">java.util.HashMap</import>
	<import>file:///${xutils.home}/config.xml</import>
	<array class="java.lang.Object" id="@number">
		<arg class="byte">0</arg>
		<arg class="int">1</arg>
		<arg class="long">2</arg>
		<arg class="short">3</arg>
		<arg class="double">4</arg>
		<arg class="float">5</arg>
		<arg class="boolean">true</arg>
		<arg class="char">C</arg>
	</array>
	<array class="byte" id="@bytearray2">
		<arg>3</arg>
		<arg>4</arg>
		<arg>5</arg>
	</array>
	<bean class="${map}" id="map" eager="true">
		<set name="empty"></set>
		<set name="string">${xutils.home}</set>
		<set name="int" class="int">124</set>
		<set name="bytearray" ref="@bytearray2" />
		<set name="objectlist" class="java.util.List" ref="@number"/>
		<set name="bytelist" class="java.util.List" ref="@bytearray2"/>
	</bean>
	<alias ref="map" id="amap">
		<aop class="java.util.Map"/>
	</alias>
	<bean class="zcu.xutil.cfg.Book" id="numb" cache="false">
		<arg>numb</arg>
		<arg class="double">1</arg>
		<arg>2</arg>
	</bean>
	<bean class="zcu.xutil.cfg.Store" id="mystoreMap">
			<arg>
				<bean class="java.util.HashMap">
					<set name="REFbook" ref="numb"></set>
					<set name="NEWbook">
						<bean class="zcu.xutil.cfg.Book">

								<arg>innnnnrrrrr</arg>
								<arg class="double">1</arg>
								<arg>2</arg>

						</bean>
					</set>
				</bean>
			</arg>
	</bean>
	<bean class="zcu.xutil.cfg.Store" id="mystore" destroy="xx">
			<arg>${mystore}</arg>
			<arg>
				<array class="zcu.xutil.cfg.Book">
					<arg ref="numb"/>
				</array>
			</arg>
	</bean>
	<array class="byte" id="bytearray">
		<arg>1</arg>
		<arg>3</arg>
		<arg>5</arg>
	</array>
	<bean class="int" id="int">

			<arg><![CDATA[999999]]></arg>

	</bean>


	<bean class="zcu.xutil.FirstBean" id="firstBean">
		<set name="firstString">${}</set>
		<call name="setFirstInteger">
			<arg>9999</arg>
		</call>
		<set name="firstInt" ref="int" />
		<set name="firstbytes" ref="bytearray" />
	</bean>
	

	<bean id="staticFactory" class="java.net.URL" from="zcu.xutil.Objutil:toURL">
		<arg class="java.io.File">${xutils.home}</arg>
	</bean>
	<bean class="zcu.xutil.FirstBean" id="output" out="getFirstString">
		<set name="firstString">oooooooooo</set>
		<call name="setFirstInteger">
			<arg>9999</arg>
		</call>
		<set name="firstInt" ref="int" />
		<set name="firstbytes" ref="bytearray" />
	</bean>
	<bean class="zcu.xutil.FirstBean" id="bean2">
		<set name="firstString">oooooooooo</set>
		<call name="setFirstInteger">
			<arg>9999</arg>
		</call>
		<set name="firstInt" ref="int" />
		<set name="firstbytes">
			<array class="byte">
				<arg>1</arg>
				<arg>3</arg>
				<arg>5</arg>
			</array>
		</set>
	</bean>
	<bean class="java.lang.String" id="factory" from="bean2:getFirstString"/>
</beans>

=== nbeeee/xutils/xutils/src/test/java/xutils-root.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE beans PUBLIC "-//XUTILS//DTD CONFIG//EN" "xutils-config.dtd">
<beans>
	<import>testScript.js</import>
	<bean id="h2ds" class="zcu.xutil.txm.SmartDataSource">
		<arg>
			<bean class="zcu.xutil.sql.MiniDataSource" destroy="destroy">
				<arg>
					<bean class="org.h2.jdbcx.JdbcDataSource">
						<set property="URL">jdbc:h2:~/h2db/test;DB_CLOSE_DELAY=-1</set>
						<set property="user">sa</set>
					</bean>
				</arg>
				<arg>4</arg>
				<arg>8</arg>
			</bean>
		</arg>
	</bean>
	<bean id="query" class="zcu.xutil.sql.Query">
		<arg ref="h2ds" />
	</bean>
	
</beans>
